# 章节1：大语言模型概论
- 庞大规模： 数十亿或数万亿参数 (parameter)。
- 广泛训练数据： 在数TB或数PB的多样化文本上进行预训练 (pre-training)。
- Transformer架构： 通常基于Transformer模型。
- 涌现 (emergence)能力： 表现出零样本和少样本学习 (few-shot learning)能力，这些能力并非其明确的训练目标。
- 高昂计算成本： 训练需要大规模分布式计算资源。

---


## 整体概览

LLM的系统环境包含这些组件的协作。数据被获取并存储，然后使用Spark等工具进行大规模预处理。分词 (tokenization)器 (tokenizer)为模型准备文本。训练期间，分布式库使用PyTorch等深度学习 (deep learning)框架，协调在多个加速器（GPU/TPU）上的执行。高速互连促进设备间必要的通信。实验追踪工具监控整个过程，检查点保存到可靠的存储中。这种配置使得能够开发和训练大型语言模型所需规模的模型。

数据存储
(S3, GCS, NFS)
数据预处理
(Spark, Dask, HF Datasets)



# 章节2：大型语言模型的数学预备知识

## 线性代数



In [5]:
! uv pip install torch

Resolved 30 packages in 13.56s
 Downloaded setuptools
 Downloaded networkx
 Downloaded torch
Prepared 4 packages in 55.91s
Installed 9 packages in 10.33s
 + filelock==3.29.6
 + fsspec==2026.6.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.6.1
 + setuptools==81.0.0
 + sympy==1.14.0
 + torch==2.12.1
Using Python 3.12.13 environment at: d:\demo\summer_model\.venv
Checked 1 package in 29.36s


In [ ]:
# 逐元素运算（哈达玛积）
import torch

A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[0.5, 1.], [-1., 2.]])

# 逐元素乘法
C = A * B # 或者 torch.multiply(A, B)

print(f"矩阵 A:\n{A}")
print(f"矩阵 B:\n{B}")
print(f"逐元素乘积 C:\n{C}")


d:\demo\summer_model\.venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


矩阵 A:
tensor([[1., 2.],
        [3., 4.]])
矩阵 B:
tensor([[ 0.5000,  1.0000],
        [-1.0000,  2.0000]])
逐元素乘积 C:
tensor([[ 0.5000,  2.0000],
        [-3.0000,  8.0000]])


In [9]:
# 范数
import torch

v = torch.tensor([3.0, -4.0, 0.0])

l2_norm = torch.linalg.norm(v, ord=2)
l1_norm = torch.linalg.norm(v, ord=1)

print(f"L2 范数：{l2_norm}")
print(f"L1 范数：{l1_norm}")



L2 范数：5.0
L1 范数：7.0


# 微积分：梯度与优化


In [11]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=False)
w = torch.tensor([0.5, -0.1, 0.2], requires_grad=True)
b = torch.tensor(0.1, requires_grad=True)
y = torch.dot(w, x) + b

loss = y.square()

loss.backward()

print(f"w:{w.grad}")
print(f"b:{b.grad}")

y_val = (0.5 * 1.0 + (-0.1) * 2.0 + 0.2 * 3.0 + 0.1)
grad_w1_manual = 2 * y_val * x[0]

print(f"手动计算的 w_1 梯度: {grad_w1_manual}")

w:tensor([2., 4., 6.])
b:2.0
手动计算的 w_1 梯度: 2.0


# 概率与统计基础知识
# 数值稳定性考量
 梯度消失  梯度爆炸